import {DisplayOffer} from "../types/DisplayOffer";

export const mockJobOffers = () =>{
  const jobs: DisplayOffer[] = [
    {
      _id: "6494777e8d3741c686d52828",
      company_name: "Diamond Photography",
      days_ago: "1684910110500",
      contract_types: "Full Time",
      country: "Remote",
      ad_content: "Junior Frontend Developer",
      job_type: "Frontend",
      seniority: "Junior",
      technology_1: "React",
      technology_2: "TypeScript",
      technology_3: "Node.js",
      salary: "8998 $",
      description:
        "Last couple of years changed everything about workplace collaboration. For better or worse, millions of knowledge workers around the globe said adios to their office cubicles and embraced work-from-home / work-from-anywhere culture. This wave brought a whole new set of challenges & opportunities to team collaboration, knowledge sharing & project management.\n\nSkills & Experience:\n➔ Relevant professional experience (0.5+ year) with front-end technologies, - React, Node.js, Typescript. Whereas we appreciate some breadth, we value the depth even more!\n➔ Attention to detail, passion for UX;\n➔ Willingness to learn and use multiple technologies;\n➔ Truly engineering approach to solving problems. Good theoretical foundations of computer science(e.g. algorithms and computational complexity, OOP) are super practical in the ever-changing landscape of technologies;\n➔ Basic understanding of the architecture of web applications;\n➔ Command of English at level B2 or higher;\n➔ Contributions to any open source projects are a big advantage.",
      about_us:
        "Diamond Photography is a photography brand sourced from the UK. We offer a range of photography packs including wedding photography, engagement photography, family photography, travel photography, and portrait photography.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Diamond%20Photography.png",
      isDescriptionVisible: false,
      frontendId: 0,
    },
    {
      _id: "6494777e8d3741c686d52829",
      company_name: "Yorke Cycles",
      days_ago: "1684870110100",
      contract_types: "Contract",
      country: "Australia",
      ad_content: "Senior Frontend Developer",
      job_type: "Frontend",
      seniority: "Senior",
      technology_1: "Knockout",
      technology_2: "JavaScript",
      technology_3: "TypeScript",
      salary: "8239 $",
      description:
        "Together with our partner – a leading provider of technologies supporting sport performance – we would love to invite Frontend-oriented engineers to co-create our projects. \n\nOne of them is e-learning platform. The platform is free for anybody in the world to use and take courses and certifications in understanding the many aspects of the sport of cycling.\n\nSkills & Experience:\n➔ Proven professional experience as a Frontend Developer (senior or lead) \n➔ Strong JavaScript, TypeScript, HTML, CSS, SASS, React, Knockout\n➔ Experience in working with coding standards and static code analysis tools (ESLint, Prettier) \n➔ Experience in working with CI/CD tools and procedures (Git) \n➔ Good all around knowledge of the following: Client/server architecture, JSON Web Tokens, OAuth \n➔ Experience in testing, e.g. unit tests, integration tests \n➔ English language at the level of min. B2",
      about_us:
        "Yorke Cycles is a family-owned and operated bike shop in Sydney, Australia. We specialise in custom frames and steel road, mountain and hybrid bikes, along with various accessories. We also sell new and used road and mountain bike parts.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Yorke%20Cycles.png",
      isDescriptionVisible: false,
      frontendId: 1,
    },
    {
      _id: "6494777e8d3741c686d5282a",
      company_name: "Lear Finishing Ltd",
      days_ago: "1684850910360",
      contract_types: "Full Time",
      country: "Peru",
      ad_content: "Fullstack Developer",
      job_type: "Fullstack",
      seniority: "Senior",
      technology_1: "Python",
      technology_2: "React",
      technology_3: "TypeScript",
      salary: "7661 $",
      description:
        "We are looking for a Senior Full-stack (Python/React) Developer with solid knowledge in Python, Typescript, and React to join our project with General Catalyst, a renowned venture capital firm based in the US, and take part in the solution architecture processes.\n\nSkills & Experience:\n➔ 4+ years of experience in the full software development life-cycle and knowledge of Python, Typescript, and React;\n➔ Proficiency with Python;\n➔ Experience with modern JavaScript frameworks;\n➔ Experience with relational and distributed databases (including internals, e.g., PostgreSQL, MySQL, Cassandra, etc.);\n➔ Proven ability for high-quality delivery;\n➔ Strong interest in new technologies and willingness to learn them;\n➔ Experienced with GCP Cloud technologies; \n➔ Experience in the implementation of REST API;\n➔ Experience in writing tests (the whole test pyramid: unit/integration/end-to-end);\n➔ Full-stack development experience on high-scale systems;\n➔ Solid Computer Science background;\n➔ Product-focused team player mindset.",
      about_us:
        "Lear Finishing Ltd is a hardwood flooring and flooring accessories specialist with a strong emphasis on customer service in a modern, high-tech environment.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Lear%20Finishing%20Ltd.png",
      isDescriptionVisible: false,
      frontendId: 2,
    },
    {
      _id: "6494777e8d3741c686d5282b",
      company_name: "Riverside Transport",
      days_ago: "1684849910310",
      contract_types: "Contract",
      country: "South of England",
      ad_content: "Senior Frontend Developer",
      job_type: "Frontend",
      seniority: "Senior",
      technology_1: "Python",
      technology_2: "React",
      technology_3: "Django",
      salary: "2519 $",
      description:
        "Fullstack engineer for British transport startup. In this role you will have the opportunity to share the expertise with less cloud-capable colleagues, to understand requirements and lead and support them to deliver enterprise-class solutions.\n\nSkills & Experience:\n➔ Minimum 5 years of experience in main technology.\n➔ Highly motivated, with a track record of driving ideas forwards and taking ownership of complex problems \n➔ Mastery of Python, with a real comfort working in the language\n➔ Front-end React framework proficiency ·\n➔ Intimate knowledge of Django (Including DRF and Django ORM) or knowledge of other Python frameworks e.g. Fast API, Flask ·\n➔ Proven ability with database technologies such as Postgres, Snowflake, or Oracle.",
      about_us:
        "Riverside Transport is an independent transport company operating in the South of England and serving all surrounding areas. We are a family run business and pride ourselves on our personal customer service and quality of work.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Riverside%20Transport.png",
      isDescriptionVisible: false,
      frontendId: 3,
    },
    {
      _id: "6494777e8d3741c686d5282c",
      company_name: "Dimbleby Refrigeration",
      days_ago: "1684809910310",
      contract_types: "Contract",
      country: "UK only",
      ad_content: "Middle Developer",
      job_type: "Python",
      seniority: "Midweight",
      technology_1: "C#",
      technology_2: "HTML5",
      technology_3: "JavaScript",
      salary: "4622 $",
      description:
        "At Dimbleby Refrigeration we formed our software development teams around a matrixed organization where team members belong to a chapter, in which their skills, competencies and standards are solidified and grown.  They are also members of a Squad where they utilize those skills and competencies to support the squad to be a self-sustaining team able to build and release quality software.  Squads belong to a Tribe, which coordinates and ensures the squad’s focus and output are aligned to support services and solutions for a product or vertical. \n\nSkills & Experience:\n➔ 2 to 5 years of working experience\n➔ Working knowledge of C# and HTML5\n➔ Solid understanding of frontend technologies and concepts\n➔ Must work effectively with others in a team environment\n➔ Strong development fundamentals\n➔ Strong written and verbal English communication skills\n➔ Vue.js, javascript, typescript experience preferred but not required\n➔ QT/QML considered a benefit\n➔ Experience in AWS",
      about_us:
        "Dimbleby Refrigeration has been providing refrigeration and air conditioning services to the commercial and industrial markets for over 70 years.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Dimbleby%20Refrigeration.png",
      isDescriptionVisible: false,
      frontendId: 4,
    },
    {
      _id: "6494777e8d3741c686d5282d",
      company_name: "O'Grady Exhibitions",
      days_ago: "1684759910310",
      contract_types: "Contract",
      country: "USA only",
      ad_content: "Senior Frontend Developer",
      job_type: "Frontend",
      seniority: "Senior",
      technology_1: "React",
      technology_2: "Bootstrap",
      technology_3: "TypeScript",
      salary: "9465 $",
      description:
        "At O'Grady Exhibitions, we believe in developing potential so we’re not looking for the perfect candidate with gold medals and superpowers. Even if you don’t have everything listed below, if you think you could be great in this role please do apply.  We want to hear from you. Truly!\n\nSkills & Experience:\n➔ A keen interest in writing resilient software that scales\n➔ Solid experience with React and Typescript\n➔ Knowledge of testing (Jest, React testing library)\n➔ Familiarity with Bootstrap and REST API\n➔ Experience with GraphQL",
      about_us:
        "O'Grady Exhibitions is a company that produces exhibition stands and flagpoles for large events, corporate events and weddings. The company offers a variety of different designs, materials and finishes.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/O'Grady%20Exhibitions.png",
      isDescriptionVisible: false,
      frontendId: 5,
    },
    {
      _id: "6494777e8d3741c686d5282e",
      company_name: "Fine Hire Cars Ltd",
      days_ago: "1684719910310",
      contract_types: "Contract",
      country: "USA only",
      ad_content: "Senior Frontend Developer",
      job_type: "Frontend",
      seniority: "Senior",
      technology_1: "C#",
      technology_2: "JavaScript",
      technology_3: "React",
      salary: "4309 $",
      description:
        "Simply, at Fine Hire Cars Ltd we are trying to provide the perfect conditions for work and personal development. Currently we are searching for Senior Frontend Developers with React or Angular to join our long-term projects.\n\nSkills & Experience:\n➔ 6+ years of experience in frontend development roles\n➔ 4+ years of experience in React/Redux or Angular\n➔ Treating testing as inherent part of the work\n➔ Autonomy and responsibility combined with strong communication skills\n➔ Problem solving approach – we’re oriented to deliver solutions instead of digging deeper into academic discussions\n➔ If you are also skilled in backend technologies (Python, Node.js) or willing to become a Fullstack - it sounds like a great match for us, as we strongly support this direction of professional development!",
      about_us:
        "The all-new Fine Hire Cars Ltd. is a UK-based, family business specialising in car hire and car leasing. We provide an honest and straightforward service, at a competitive price, with a friendly and helpful approach. We are the only hire car company to have our own fleet of",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Fine%20Hire%20Cars%20Ltd.png",
      isDescriptionVisible: false,
      frontendId: 6,
    },
    {
      _id: "6494777e8d3741c686d5282f",
      company_name: "Expert Technologies",
      days_ago: "1684699910310",
      contract_types: "Part Time",
      country: "Remote",
      ad_content: "Software Engineer",
      job_type: "Fullstack",
      seniority: "Senior",
      technology_1: "C#",
      technology_2: "React",
      technology_3: "JavaScript",
      salary: "8613 $",
      description:
        "Expert Technologies combines top-level IT skills and deep financial knowledge to deliver innovative products and services. We are a Developers Driven Company, you will meet people with high programming skills and will participate in exciting projects here. Founded by People with international experience - alumni of Warsaw University, Faculty of Mathematics, Informatics and Mechanics (MIM). We worked at top-tier investment banks and hedge funds in London for several years. We implement projects for clients from the financial sectors across Europe and the US. \n\nSkills & Experience:\n➔ Advanced knowledge of software design, data structures and algorithms\n➔ Strong interpersonal and communication skills, openness to direct work with customers \n➔ Exposure to multiple programming languages and paradigms.\n➔ Familiarity with cloud computing such as AWS / Azure / GCP is a plus\n➔ Financial knowledge and/or experience in financial markets will be an advantage\n➔ Very good command of English",
      about_us:
        "Expert Technologies is a Top-100 independent, worldwide IT service provider with services and solutions for customers in more than 100 countries.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Expert%20Technologies.png",
      isDescriptionVisible: false,
      frontendId: 7,
    },
    {
      _id: "6494777e8d3741c686d52830",
      company_name: "Silver Fabrics",
      days_ago: "1684659910310",
      contract_types: "Part Time",
      country: "Worldwide",
      ad_content: "Junior Developer",
      job_type: "Frontend",
      seniority: "Junior",
      technology_1: "HTML",
      technology_2: "CSS",
      technology_3: "TypeScript",
      salary: "2242 $",
      description:
        "Take your first step in the IT world.  Join our customer's internship program to gain experience and work on software development projects. Extend your knowledge and upgrade your skills.  Say ‘yes’ to a new career opportunity and join the team as a Junior Frontend Developer. \n\nSkills & Experience:\n➔ Experience in Java Script, CSS, HTML \n➔ Good communication skills \n➔ Analytical and critical thinking \n➔ Ability to work well with a team",
      about_us:
        "Silver Fabrics is the world's oldest, largest and most comprehensive fabric brand, providing design inspiration for over 100 years.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Silver%20Fabrics.png",
      isDescriptionVisible: false,
      frontendId: 8,
    },
    {
      _id: "6494777e8d3741c686d52831",
      company_name: "Anderton Lab Equipment Ltd",
      days_ago: "1684559910310",
      contract_types: "Full Time",
      country: "Belarus",
      ad_content: "Fullstack Developer",
      job_type: "Fullstack",
      seniority: "Junior",
      technology_1: "C++",
      technology_2: "XML",
      technology_3: "SQL",
      salary: "4432 $",
      description:
        "As a global company spanning multiple regions and offering limitless opportunities for growth, we believe that everyone should be an entrepreneur of their role. At Infor, there are countless opportunities for you to be challenged and contribute towards transformative growth. Sounds exciting? Apply today!\n\nSkills & Experience:\n➔ C++ (C++11, C++14, STL, generic programming using templates) knowledge\n➔ Database and SQL technologies knowledge\n➔ Competent in Network technologies and XML processing\n➔ Ability to interface professionally with global development teams\n➔ Ability to solve unconventional problems and analytical thinking\n➔ Professional demeanor and appearance\n➔ Good verbal and written communication skills\n➔ English language proficiency",
      about_us:
        "Anderton Lab Equipment Ltd. provides scientific laboratory equipment and services. Products include stamper and die making, testing and calibration equipment, computer controlled equipment, and more.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Anderton%20Lab%20Equipment%20Ltd.png",
      isDescriptionVisible: false,
      frontendId: 9,
    },
    {
      _id: "6494777e8d3741c686d52832",
      company_name: "Ingram Automotive Ltd",
      days_ago: "1681559910310",
      contract_types: "Full Time",
      country: "Holy See (Vatican City State)",
      ad_content: "Fullstack Developer",
      job_type: "Fullstack",
      seniority: "Midweight",
      technology_1: "React",
      technology_2: "Python",
      technology_3: "TypeScript",
      salary: "9455 $",
      description:
        "Our partner’s car stock photo library is the gold standard for automotive imagery, offering the highest quality vehicle multimedia assets for commercial use. They continuously pioneer top-of-the-line technology to provide unparalleled coverage and speed to market for automotive stock photos, car stock videos and virtual reality assets. It would be ideal for someone who enjoys working in a team, solving technical problems as well as believes in making a purposeful and positive impact around them.\n\nSkills & Experience:\n➔ At least 2 years experience with ReactJS and Typescript\n➔ Strong experience with Python\n➔ Some experience with AWS infrastructure\n➔ Some experience with Docker\n➔ Good knowledge with relational databases (RDBMS)\n➔ Experience with continuous integration (CI/CD pipeline)\n➔ Familiarity with GraphQL\n➔ Familiarity with code management and deployment solutions (Git, Rez, Pip, Salt)\n➔ Familiarity with Mac and Linux OS level programming;",
      about_us:
        "Ingram Automotive Ltd is a leading distributor of automotive and industrial products in the United Kingdom.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Ingram%20Automotive%20Ltd.png",
      isDescriptionVisible: false,
      frontendId: 10,
    },
    {
      _id: "6494777e8d3741c686d52833",
      company_name: "Ingeman Workshops",
      days_ago: "1679559910310",
      contract_types: "Part Time",
      country: "Remote",
      ad_content: "Junior Backend Developer",
      job_type: "Backend",
      seniority: "Junior",
      technology_1: "RoR",
      technology_2: "Ruby",
      technology_3: "SQL",
      salary: "7004 $",
      description:
        "We're a hard-working, fun-loving, get-things-done type of team that is building a platform that helps increase client’s online sales. We know how much grit it takes to start your own business and grow it into something that lasts. We roll our sleeves up, we act fast, and we learn together. We're looking for people that will do the same.\n\nSkills & Experience:\n➔ Java or any other backend language with willingness to switch to Java - junior\n➔ SQL - junior\n➔ Git - junior\n➔ English - B2+\n➔ Willingness to share knowledge",
      about_us:
        "Ingeman Workshops is a premier, non-traditional business workshop facilitator in the UK, running small group workshops for companies of all sizes.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Ingeman%20Workshops.png",
      isDescriptionVisible: false,
      frontendId: 11,
    },
    {
      _id: "6494777e8d3741c686d52834",
      company_name: "Saddlemore Office Furniture",
      days_ago: "1674559910310",
      contract_types: "Contract",
      country: "UK only",
      ad_content: "Middle Developer",
      job_type: "C#",
      seniority: "Midweight",
      technology_1: "C#",
      technology_2: "Node.js",
      technology_3: "TypeScript",
      salary: "9288 $",
      description:
        "You’ll be responsible for creating frontend and backend of web applications based on graphic design and technical specifications.\n\nSkills & Experience: \n➔ knowledge of HTML5, JavaScript (REST), TypeScript, CSS3, Vue, NuxtJs, Vuetify (or experience in similar frameworks),\n➔ experience in RWD / mobile, SPA designing and programming,\n➔ knowledge of REST api architecture,\n➔ knowledge of Git,\n➔ knowledge of NodeJS, framework - NestJS (TypeScript),\n➔ knowledge of database technologies SQL (MySQL) / NoSQL,\n➔ general knowledge of backend architecture and serverless architecture,\nGCP,\n➔ at least 1-year of experience in a similar role,\n➔ very good written and verbal communication skills in English.",
      about_us:
        "Saddlemore Office Furniture is a leading company in office furniture design and production, serving the commercial and corporate markets. Saddlemore office furniture products are manufactured using the finest materials and the most modern technology, ensuring that they meet the highest quality and design standards.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Saddlemore%20Office%20Furniture.png",
      isDescriptionVisible: false,
      frontendId: 12,
    },
    {
      _id: "6494777e8d3741c686d52826",
      company_name: "Sutton Builders",
      days_ago: "1685097120267",
      contract_types: "Full Time",
      country: "Remote",
      ad_content: "Junior Frontend Developer",
      job_type: "Frontend",
      seniority: "Junior",
      technology_1: "JavaScript",
      technology_2: "React",
      technology_3: "CSS",
      salary: "3872 $",
      description:
        "We are currently developing a team of world-class Frontend Developers obsessed with React.js.\nYou must be passionate and willing to act! At this point, you don’t have to be the absolute best and the most experienced, but this must be your goal. We're looking for a Growth - Minded person.\n\nSkills & Experience:\n➔ knowledge hungry\n➔ at least 1 year of commercial experience within web development \n➔ understands basic JS concepts (ES 2016+)\n➔ basic experience with at least one frontend framework (React.js preferred)\n➔ English level min. B2 language skills",
      about_us:
        "Sutton Builders have been delivering high quality, attractive and affordable homes since 1912. Swindon based with a national reputation for trust, quality and service. Sutton Builders are the developers of the award winning Sutton Park and Sutton Place.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Sutton%20Builders.png",
      isDescriptionVisible: false,
      frontendId: 13,
    },
    {
      _id: "6494777e8d3741c686d52827",
      company_name: "Leonard Kitchens Ltd",
      days_ago: "1684930320000",
      contract_types: "Contract",
      country: "Worldwide",
      ad_content: "Front-end Dev",
      job_type: "Frontend",
      seniority: "Junior",
      technology_1: "Rest",
      technology_2: "Soap",
      technology_3: "XML",
      salary: "3680 $",
      description:
        "Leonard Kitchens Ltd is a great place to work for ambitious, open-minded and responsible people. We have been implementing the most innovative customer experience solutions for our clients since 2005. We believe that our success comprises not only modern technologies we use but, above all, well trained, competent people. We are In Touch with Tomorrow helping our clients rise and develop faster.\n\nSkills & Experience:\n➔ Technical background backed up by knowledge of at least one of the below\n➔ Practical knowledge of XML, JSON, XPath, XSLT\n➔ Academic level knowledge/experience in object oriented programming (Java, C++, C#, .NET, Salesforce, etc)\n➔ Experience with web service operations (SOAPUI or Postman)\n➔ English language skills enabling to work in a communicative way in an international team\n➔ Higher education in computer science or related (students welcome)\n➔ Analytical mindset, focused on the problem solving\n➔ Ability to work in a team\n➔ A flexible approach, adapting style of work to be successful working with both small and large clients",
      about_us:
        "Leonard Kitchens Ltd is a well known and highly respected UK based manufacturer of quality kitchen and bathroom products. We design, manufacture and supply a large range of furniture products, including kitchen cabinets, bathroom vanities, white goods and mirrors.",
      logo: "https://raw.githubusercontent.com/ajgoras/job-search-mern/main/csv/images/Leonard%20Kitchens%20Ltd.png",
      isDescriptionVisible: false,
      frontendId: 14,
    },
  ];
  return jobs;
}